import { normalizeDestination } from "./destination";

const DESTINATION_HIGHLIGHT_CATALOG: Record<string, string[]> = {
  manali: [
    "Hadimba Devi Temple",
    "Solang Valley",
    "Old Manali",
    "Vashisht Temple and Hot Springs",
    "Jogini Falls",
    "Mall Road Manali",
  ],
  nainital: [
    "Naini Lake",
    "Naina Devi Temple",
    "Snow View Point",
    "The Mall Road",
    "Tiffin Top",
    "Eco Cave Gardens",
  ],
  shimla: [
    "The Ridge",
    "Mall Road Shimla",
    "Jakhoo Temple",
    "Kufri",
    "Christ Church Shimla",
    "Scandal Point",
  ],
  mussoorie: [
    "Kempty Falls",
    "Gun Hill",
    "Camel's Back Road",
    "Mall Road Mussoorie",
    "Lal Tibba",
    "Company Garden",
  ],
  darjeeling: [
    "Tiger Hill",
    "Batasia Loop",
    "Darjeeling Himalayan Railway",
    "Peace Pagoda",
    "Chowrasta Mall",
    "Padmaja Naidu Himalayan Zoo",
  ],
  ooty: [
    "Ooty Lake",
    "Government Botanical Garden",
    "Doddabetta Peak",
    "Rose Garden Ooty",
    "Tea Museum",
    "Pykara Lake",
  ],
  goa: [
    "Baga Beach",
    "Calangute Beach",
    "Fort Aguada",
    "Old Goa Churches",
    "Anjuna Beach",
    "Panaji Latin Quarter",
  ],
  jaipur: [
    "Amber Fort",
    "City Palace Jaipur",
    "Hawa Mahal",
    "Jantar Mantar",
    "Nahargarh Fort",
    "Johari Bazaar",
  ],
  udaipur: [
    "City Palace Udaipur",
    "Lake Pichola",
    "Jag Mandir",
    "Sajjangarh Monsoon Palace",
    "Bagore Ki Haveli",
    "Fateh Sagar Lake",
  ],
  rishikesh: [
    "Laxman Jhula",
    "Ram Jhula",
    "Triveni Ghat",
    "Parmarth Niketan",
    "Beatles Ashram",
    "Neer Garh Waterfall",
  ],
  haridwar: [
    "Har Ki Pauri",
    "Mansa Devi Temple",
    "Chandi Devi Temple",
    "Bharat Mata Mandir",
    "Ganga Aarti Ghat",
    "Shantikunj",
  ],
  varanasi: [
    "Dashashwamedh Ghat",
    "Kashi Vishwanath Temple",
    "Assi Ghat",
    "Sarnath",
    "Manikarnika Ghat",
    "Banaras Hindu University",
  ],
  tirupati: [
    "Sri Venkateswara Temple",
    "Sri Padmavathi Ammavari Temple",
    "Akasaganga Teertham",
    "Silathoranam",
    "Kapila Theertham",
    "Chandragiri Fort",
  ],
  dwarka: [
    "Dwarkadhish Temple",
    "Bet Dwarka",
    "Rukmini Devi Temple",
    "Gomti Ghat",
    "Nageshwar Jyotirlinga",
    "Dwarka Beach",
  ],
  somnath: [
    "Somnath Temple",
    "Triveni Sangam Somnath",
    "Bhalka Tirth",
    "Somnath Beach",
    "Prabhas Patan Museum",
    "Gita Mandir",
  ],
  ayodhya: [
    "Shri Ram Janmabhoomi Mandir",
    "Hanuman Garhi",
    "Kanak Bhawan",
    "Saryu Ghat",
    "Dashrath Mahal",
    "Ram Ki Paidi",
  ],
  mumbai: [
    "Gateway of India",
    "Marine Drive",
    "Colaba Causeway",
    "Elephanta Caves",
    "Juhu Beach",
    "Siddhivinayak Temple",
  ],
  london: [
    "Buckingham Palace",
    "Tower Bridge",
    "British Museum",
    "Westminster Abbey",
    "Covent Garden",
    "London Eye",
  ],
  paris: [
    "Eiffel Tower",
    "Louvre Museum",
    "Montmartre",
    "Seine River Cruise",
    "Notre-Dame Area",
    "Champs-Elysees",
  ],
  dubai: [
    "Burj Khalifa",
    "Dubai Mall",
    "Dubai Marina",
    "Palm Jumeirah",
    "Jumeirah Beach",
    "Old Dubai Souks",
  ],
  singapore: [
    "Marina Bay Sands",
    "Gardens by the Bay",
    "Sentosa Island",
    "Merlion Park",
    "Chinatown Singapore",
    "Clarke Quay",
  ],
  tokyo: [
    "Senso-ji Temple",
    "Shibuya Crossing",
    "Tokyo Skytree",
    "Meiji Shrine",
    "Asakusa",
    "Shinjuku",
  ],
  barcelona: [
    "Sagrada Familia",
    "Park Guell",
    "La Rambla",
    "Gothic Quarter",
    "Casa Batllo",
    "Barceloneta Beach",
  ],
  newyork: [
    "Times Square",
    "Central Park",
    "Statue of Liberty",
    "Brooklyn Bridge",
    "Fifth Avenue",
    "Empire State Building",
  ],
  leh: [
    "Shanti Stupa",
    "Leh Palace",
    "Hall of Fame",
    "Magnetic Hill",
    "Sangam Point",
    "Thiksey Monastery",
  ],
  "leh ladakh": [
    "Shanti Stupa",
    "Leh Palace",
    "Hall of Fame",
    "Magnetic Hill",
    "Sangam Point",
    "Thiksey Monastery",
  ],
  kasol: [
    "Parvati River Walk",
    "Chalal Village",
    "Manikaran Sahib",
    "Kasol Market",
    "Tosh Viewpoint",
    "Nature Park Kasol",
  ],
  auli: [
    "Auli Ropeway",
    "Auli Artificial Lake",
    "Gurso Bugyal",
    "Joshimath",
    "Kwani Bugyal",
    "Nanda Devi Viewpoint",
  ],
  pondicherry: [
    "Promenade Beach",
    "Sri Aurobindo Ashram",
    "White Town",
    "Paradise Beach",
    "Auroville",
    "Basilica of the Sacred Heart",
  ],
  kerala: [
    "Munnar Tea Gardens",
    "Alleppey Backwaters",
    "Fort Kochi",
    "Thekkady",
    "Kovalam Beach",
    "Athirappilly Waterfalls",
  ],
  andaman: [
    "Radhanagar Beach",
    "Cellular Jail",
    "Elephant Beach",
    "Ross Island",
    "Corbyn's Cove",
    "Bharatpur Beach",
  ],
  lakshadweep: [
    "Agatti Island",
    "Bangaram Island",
    "Kavaratti",
    "Kalpeni Island",
    "Marine Museum Kavaratti",
    "Lagoon Beachfront",
  ],
  gokarna: [
    "Om Beach",
    "Kudle Beach",
    "Mahabaleshwar Temple",
    "Half Moon Beach",
    "Paradise Beach",
    "Gokarna Main Beach",
  ],
  mysore: [
    "Mysore Palace",
    "Chamundi Hills",
    "St. Philomena's Church",
    "Devaraja Market",
    "Brindavan Gardens",
    "Jaganmohan Palace",
  ],
  jodhpur: [
    "Mehrangarh Fort",
    "Jaswant Thada",
    "Clock Tower Market",
    "Umaid Bhawan Palace",
    "Mandore Gardens",
    "Toorji Ka Jhalra",
  ],
  jaisalmer: [
    "Jaisalmer Fort",
    "Patwon Ki Haveli",
    "Gadisar Lake",
    "Sam Sand Dunes",
    "Bada Bagh",
    "Nathmal Ki Haveli",
  ],
  mathura: [
    "Shri Krishna Janmabhoomi",
    "Dwarkadhish Temple Mathura",
    "Vishram Ghat",
    "Govardhan Hill",
    "Kusum Sarovar",
    "Vrindavan Banke Bihari Temple",
  ],
  ujjain: [
    "Mahakaleshwar Temple",
    "Kal Bhairav Temple",
    "Ram Ghat",
    "Harsiddhi Temple",
    "Sandipani Ashram",
    "Vedh Shala Ujjain",
  ],
  shirdi: [
    "Sai Baba Samadhi Mandir",
    "Dwarkamai",
    "Chavadi",
    "Gurusthan",
    "Lendi Baug",
    "Khandoba Temple",
  ],
  nashik: [
    "Trimbakeshwar Temple",
    "Panchavati",
    "Sula Vineyards",
    "Ramkund",
    "Pandavleni Caves",
    "Godavari Ghat",
  ],
  spiti: [
    "Key Monastery",
    "Kibber Village",
    "Chandratal Lake",
    "Langza",
    "Hikkim",
    "Kaza Market",
  ],
  "spiti valley": [
    "Key Monastery",
    "Kibber Village",
    "Chandratal Lake",
    "Langza",
    "Hikkim",
    "Kaza Market",
  ],
  jimcorbett: [
    "Dhikala Zone",
    "Bijrani Zone",
    "Garjia Temple",
    "Corbett Falls",
    "Sitabani Forest",
    "Kosi River Edge",
  ],
  "jim corbett": [
    "Dhikala Zone",
    "Bijrani Zone",
    "Garjia Temple",
    "Corbett Falls",
    "Sitabani Forest",
    "Kosi River Edge",
  ],
  ranthambore: [
    "Ranthambore Fort",
    "Padam Talao",
    "Safari Zones",
    "Jogi Mahal",
    "Raj Bagh Ruins",
    "Surwal Lake",
  ],
  kaziranga: [
    "Kaziranga Safari Range",
    "Orchid Park",
    "Central Range",
    "Bagori Range",
    "Tea Garden Belt",
    "Brahmaputra Riverside",
  ],
  sundarbans: [
    "Sajnekhali Watch Tower",
    "Sudhanyakhali Watch Tower",
    "Dobanki Canopy Walk",
    "Pakhiralay",
    "Bonnie Camp",
    "Gosaba Village",
  ],
  periyar: [
    "Periyar Lake",
    "Thekkady Market",
    "Periyar Wildlife Sanctuary",
    "Spice Plantations",
    "Bamboo Rafting Point",
    "Murikkady Viewpoint",
  ],
};

export const getFallbackDestinationHighlights = (destination: string) => {
  const normalized = normalizeDestination(destination).toLowerCase();

  const exactMatch = DESTINATION_HIGHLIGHT_CATALOG[normalized];
  if (exactMatch) {
    return exactMatch;
  }

  const partialMatch = Object.entries(DESTINATION_HIGHLIGHT_CATALOG).find(([key]) =>
    normalized.includes(key) || key.includes(normalized)
  );

  return partialMatch?.[1] || [];
};
